--------------------------------------------------------
--  File created - Tuesday-July-12-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BORROWED
--------------------------------------------------------

  CREATE TABLE "BORROWED"."BORROWED" 
   (	"BOOK_ID" VARCHAR2(20 BYTE), 
	"USER_ID" VARCHAR2(20 BYTE), 
	"LIBRARIAN_ID" VARCHAR2(20 BYTE), 
	"RESERVE_DATE" DATE, 
	"RETURN_DATE" DATE, 
	"DUE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into BORROWED.BORROWED
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index BORROWED_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BORROWED"."BORROWED_PK" ON "BORROWED"."BORROWED" ("BOOK_ID", "USER_ID", "LIBRARIAN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BORROWED
--------------------------------------------------------

  ALTER TABLE "BORROWED"."BORROWED" ADD CONSTRAINT "BORROWED_PK" PRIMARY KEY ("BOOK_ID", "USER_ID", "LIBRARIAN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BORROWED"."BORROWED" MODIFY ("LIBRARIAN_ID" NOT NULL ENABLE);
  ALTER TABLE "BORROWED"."BORROWED" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BORROWED"."BORROWED" MODIFY ("BOOK_ID" NOT NULL ENABLE);
