--------------------------------------------------------
--  File created - Tuesday-July-19-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence BOOK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LIBRARY"."BOOK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BOOK_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "LIBRARY"."BOOK_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BORROWED_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LIBRARY"."BORROWED_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_CUST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LIBRARY"."DEMO_CUST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_ORDER_ITEMS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LIBRARY"."DEMO_ORDER_ITEMS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_ORD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LIBRARY"."DEMO_ORD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_PROD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LIBRARY"."DEMO_PROD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LIBRARY"."DEMO_USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence LIBRARIAN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LIBRARY"."LIBRARIAN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence LIBRARIAN_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "LIBRARY"."LIBRARIAN_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REPORTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LIBRARY"."REPORTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LIBRARY"."USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BOOK
--------------------------------------------------------

  CREATE TABLE "LIBRARY"."BOOK" 
   (	"BOOK_ISBN" VARCHAR2(20 BYTE), 
	"BOOK_TITLE" VARCHAR2(200 BYTE), 
	"BOOK_AUTHOR" VARCHAR2(100 BYTE), 
	"BOOK_GENRE" VARCHAR2(50 BYTE), 
	"BOOK_EDITION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BORROWED
--------------------------------------------------------

  CREATE TABLE "LIBRARY"."BORROWED" 
   (	"BOOK_ISBN" VARCHAR2(100 BYTE), 
	"USER_ID" VARCHAR2(100 BYTE), 
	"LIBRARIAN_ID" VARCHAR2(50 BYTE), 
	"RESERVE_DATE" DATE, 
	"RETURN_DATE" DATE, 
	"DUE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LIBRARIAN
--------------------------------------------------------

  CREATE TABLE "LIBRARY"."LIBRARIAN" 
   (	"LIBRARIAN_ID" VARCHAR2(50 BYTE), 
	"LIBRARIAN_NAME" VARCHAR2(60 BYTE), 
	"LIBRARIAN_EMAIL" VARCHAR2(75 BYTE), 
	"LIBRARIAN_CONTACTNO" NUMBER, 
	"LIBRARIAN_PASS" VARCHAR2(75 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REPORTS
--------------------------------------------------------

  CREATE TABLE "LIBRARY"."REPORTS" 
   (	"REPORT_ID" VARCHAR2(20 BYTE), 
	"BOOK_ISBN" VARCHAR2(30 BYTE), 
	"USER_ID" VARCHAR2(20 BYTE), 
	"ISSUE_RETURN" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "LIBRARY"."USERS" 
   (	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_EMAIL" VARCHAR2(100 BYTE), 
	"USER_NAME" VARCHAR2(50 BYTE), 
	"USER_PHONENO" VARCHAR2(11 BYTE), 
	"USER_ADDRESS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into LIBRARY.BOOK
SET DEFINE OFF;
Insert into LIBRARY.BOOK (BOOK_ISBN,BOOK_TITLE,BOOK_AUTHOR,BOOK_GENRE,BOOK_EDITION) values ('1','mektok','abe','kelate','2');
REM INSERTING into LIBRARY.BORROWED
SET DEFINE OFF;
Insert into LIBRARY.BORROWED (BOOK_ISBN,USER_ID,LIBRARIAN_ID,RESERVE_DATE,RETURN_DATE,DUE_DATE) values ('1','1','21',to_date('14/07/2022','DD/MM/RRRR'),to_date('15/07/2022','DD/MM/RRRR'),to_date('16/07/2022','DD/MM/RRRR'));
REM INSERTING into LIBRARY.LIBRARIAN
SET DEFINE OFF;
Insert into LIBRARY.LIBRARIAN (LIBRARIAN_ID,LIBRARIAN_NAME,LIBRARIAN_EMAIL,LIBRARIAN_CONTACTNO,LIBRARIAN_PASS) values ('1','Harith','harith2312@gmail.com',197587365,'harith123');
Insert into LIBRARY.LIBRARIAN (LIBRARIAN_ID,LIBRARIAN_NAME,LIBRARIAN_EMAIL,LIBRARIAN_CONTACTNO,LIBRARIAN_PASS) values ('21','Azmi','azmi@gmail.com',92193013,'azmi123');
REM INSERTING into LIBRARY.REPORTS
SET DEFINE OFF;
REM INSERTING into LIBRARY.USERS
SET DEFINE OFF;
Insert into LIBRARY.USERS (USER_ID,USER_EMAIL,USER_NAME,USER_PHONENO,USER_ADDRESS) values ('1','harith2312@gmail.com','Harith','0197587365','Jalan Kenangan');
Insert into LIBRARY.USERS (USER_ID,USER_EMAIL,USER_NAME,USER_PHONENO,USER_ADDRESS) values ('2','azmi@gmail.com','Azmi','128478915','Jalan Kenanga');
