--------------------------------------------------------
--  File created - Wednesday-June-29-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LIBRARIAN
--------------------------------------------------------

  CREATE TABLE "BOOKS"."LIBRARIAN" 
   (	"LIBRARIAN_ID" VARCHAR2(50 BYTE), 
	"LIBRARIAN_NAME" VARCHAR2(60 BYTE), 
	"LIBRARIAN_EMAIL" VARCHAR2(75 BYTE), 
	"LIBRARIAN_CONTACTNO" NUMBER(*,0), 
	"LIBRARIAN_PASS" VARCHAR2(75 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into BOOKS.LIBRARIAN
SET DEFINE OFF;
Insert into BOOKS.LIBRARIAN (LIBRARIAN_ID,LIBRARIAN_NAME,LIBRARIAN_EMAIL,LIBRARIAN_CONTACTNO,LIBRARIAN_PASS) values ('101','Aisyah','aisyah23@gmail.com',124562345,'aisyah123');
Insert into BOOKS.LIBRARIAN (LIBRARIAN_ID,LIBRARIAN_NAME,LIBRARIAN_EMAIL,LIBRARIAN_CONTACTNO,LIBRARIAN_PASS) values ('102','Imran','imran2@gmail.com',187653456,'imran123');
Insert into BOOKS.LIBRARIAN (LIBRARIAN_ID,LIBRARIAN_NAME,LIBRARIAN_EMAIL,LIBRARIAN_CONTACTNO,LIBRARIAN_PASS) values ('103','Haziq','haziqo@gmail.com',197896758,'haziq123');
--------------------------------------------------------
--  DDL for Index LIBRARIAN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKS"."LIBRARIAN_PK" ON "BOOKS"."LIBRARIAN" ("LIBRARIAN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger LIBRARIAN_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOOKS"."LIBRARIAN_TRG" 
BEFORE INSERT ON LIBRARIAN 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.LIBRARIAN_ID IS NULL THEN
      SELECT LIBRARIAN_SEQ.NEXTVAL INTO :NEW.LIBRARIAN_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BOOKS"."LIBRARIAN_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table LIBRARIAN
--------------------------------------------------------

  ALTER TABLE "BOOKS"."LIBRARIAN" ADD CONSTRAINT "LIBRARIAN_PK" PRIMARY KEY ("LIBRARIAN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BOOKS"."LIBRARIAN" MODIFY ("LIBRARIAN_ID" NOT NULL ENABLE);
