--------------------------------------------------------
--  File created - Friday-June-24-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOOKS
--------------------------------------------------------

  CREATE TABLE "USER"."BOOKS" 
   (	"BOOK_ISBN" VARCHAR2(20 BYTE), 
	"BOOK_TITLE" VARCHAR2(200 BYTE), 
	"BOOK_AUTHOR" VARCHAR2(100 BYTE), 
	"BOOK_GENRE" VARCHAR2(50 BYTE), 
	"BOOK_EDITION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "USER"."USERS" 
   (	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_EMAIL" VARCHAR2(100 BYTE), 
	"USER_NAME" VARCHAR2(50 BYTE), 
	"USER_PHONENO" VARCHAR2(11 BYTE), 
	"USER_ADDRESS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into "USER".BOOKS
SET DEFINE OFF;
REM INSERTING into "USER".USERS
SET DEFINE OFF;
